### ISSUE TITLE
Ninguno de los comandos Yarn funciona.

### ISSUE THREAD

**Issue by fernando-inf** [GastroGeek/rixy#1]
$ yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

$ yarn build
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'build'

$ yarn lint
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'lint'

$ yarn serve
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'serve'

**Comment by GastroGeek** [comment]
@fernando-inf

Lo cloné limpiamente y funciona bien 🤔 ¿Supongo que estás en Linux? Si es así, mira esto:
https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install

El hecho de que la `yarn install` falle, sugiere que el problema es la instalación de hilo local y no el repositorio en sí.

¡Déjame saber cómo te va!

----------

I just cloned it cleanly and it works fine 🤔 I am guessing you are on Linux? If so, check out this:
https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install

The fact that `yarn install` fails, suggests its your local yarn installation that is the problem and not the repo itself.

Let me know how you get on!

**Comment by fernando-inf** [comment]
Hola, gracias por responder. Estoy usando Debian Bullseye.
Ya solucione el problema , desinstalando Yarn de los repositorios. 
Luego instale esto:
```
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update
sudo apt-get install yarn
```

Pero estoy a punto de rendirme. Webui de guitarix no muestra resultados:
Inicio: `$ guitarix -N`
Inicio: /guitarix-master/trunk/webui/websockify `$ python websocketproxy.py --web=../webui '*':8000 localhost:7000`
Y me envía a: Firefox `http://mylocalhost:8000/debug.html` -> Página en blanco.

Luego inicio RIXY con : /rixy-master `$ yarn serve`
Y me envía a: Firefox: `http://mylocalhost:8080` -> Página en blanco.

**Comment by GastroGeek** [comment]
@fernando-inf ¿configuró el archivo `.env` apuntando correctamente al puerto correcto? (en su caso 7000).

https://github.com/GastroGeek/rixy/blob/master/.env.example

Copiar `.env.example` =>` .env`

Y asegúrese de que el host / puerto apunte a la computadora en la que está ejecutando guitarix
```
VUE_APP_GUITARIX_HOST = 127.0.0.1 <<< debe apuntar a la dirección IP; también intente 192.168.0.xo cualquiera que sea la suya
VUE_APP_GUITARIX_PORT = 5000 <<< 7000 si usa el siguiente comando
```

Es posible que desee utilizar algo como esto en el host de guitarix:

```
python -m websockify.websocketproxy --web =. '*': 8000 0.0.0.0:7000
```

Especialmente si el guitarix se ejecuta en una computadora diferente a la de Rixy (pero en la misma red). "0.0.0.0" debería significar que enlaza / está disponible en "todas" las interfaces de red.

-------

Did you set the `.env` file correctly pointing to the correct port? (in your case 7000).

https://github.com/GastroGeek/rixy/blob/master/.env.example

Copy `.env.example` => `.env`

And make sure the host/port point to the computer you are running guitarix on
```
VUE_APP_GUITARIX_HOST=127.0.0.1 <<< should point to ip address - also try 192.168.0.x or whatever yours might be
VUE_APP_GUITARIX_PORT=5000 <<< 7000 if using the command below
```

You might actually want to use something like this on the guitarix host:

```
python -m websockify.websocketproxy --web=. '*':8000 0.0.0.0:7000
```

Especially if the guitarix is running on a different computer to Rixy (but on the same network). `0.0.0.0` should mean it binds/is available on `all` network interfaces.

**Comment by fernando-inf** [comment]
Gracias por responder. Ahora funciona RIXY, pero todavía no puedo hacer funcionar Guitarix Webui
Obtengo mi Hostname asi:
```
$ hostname -i
$ 127.0.1.1
```
 Luego modifique `.env.example `asi:
```
VUE_APP_GUITARIX_HOST=127.0.1.1
VUE_APP_GUITARIX_PORT=7000
```
Luego renombre` .env.example ` a `.env`
Inicio Guitarix: `$ guitarix -N --rpchost=127.0.1.1`
Inicio Server Guitarix: guitarix-master/trunk/webui/websockify`$ python websocketproxy.py --web=../ '*':8000 127.0.1.1:7000`

Inicio RIXY: `$ yarn serve`
Inicio Firefox RIXY UI: `http://127.0.1.1:8080` --> "Ensure Guitarix is running"

Entonces entro al ui de guitarix:
Inicio Firefox: `http://127.0.1.1:8000/debug.html `--> Página en Blanco

Esta es la salida de guitarix webui:

```
/guitarix-master/trunk/webui/websockify $ python  websocketproxy.py --web=../ '*':8000 127.0.1.1:7000
WebSocket server settings:
  - Listen on *:8000
  - Flash security policy server
  - Web server. Web root: /home/pc01/Descargas/guitarix-master/trunk/webui
  - No SSL/TLS support (no cert file)
  - proxying from *:8000 to 127.0.1.1:7000

  1: 127.0.0.1: "GET /build/enyo.css HTTP/1.1" 404 -
  3: 127.0.0.1: "GET /build/enyo.js HTTP/1.1" 404 -
  2: 127.0.0.1: "GET /build/app.css HTTP/1.1" 404 -
  4: 127.0.0.1: "GET /build/app.js HTTP/1.1" 404 -
  5: 127.0.0.1: "GET /enyo/enyo.js HTTP/1.1" 404 -
```
Parece que el servidor de guitarix insiste en conectarse a `127.0.0.1`, pero mi hostname es` 127.0.1.1`

**Comment by GastroGeek** [comment]
@fernando-inf 

He configurado una nueva instalación de Debian, Rixy y Guitarix y compartiré la configuración mañana

-----

Ive setup a fresh install of Debian, Rixy and Guitarix and will share settings tomorrow

**Comment by fernando-inf** [comment]
Gracias, revisaré mañana, saludos.

**Comment by GastroGeek** [comment]
¡Buenos días!

Lo hice funcionar, muy bien (aunque jack / jackd fue una pesadilla para trabajar en VirtualBox 😂)

Aquí hay algunas capturas de mi configuración. Veo que mencionaste 127.0.1.1 ... revisa tu `/ etc / hosts` y asegúrate de que sea el` localhost` y no el `debian` ... normalmente, 127.0.0.1 es el valor correcto para 'home' en un dispositivo en red a menos que tenga algunos requisitos muy específicos.

¡Espero que esto ayude!

PD: creo que el problema principal fue su `VUE_APP_GUITARIX_PORT` en Rixy ... debería apuntar al proxy (8000) y no al puerto guitarix real (7000)

------

Morning!

I got it working, just fine (although jack/jackd was a nightmare to get working in VirtualBox 😂 )

Here are some grabs of my settings. I see you mentioned 127.0.1.1... check your `/etc/hosts` and ensure that is the `localhost` and not the `debian`... normally, 127.0.0.1 is the correct value for 'home' on a networked device unless you have some very specific requirements.

Hope this helps!

PS - I think the main issue was your `VUE_APP_GUITARIX_PORT` in Rixy... it should point to the proxy (8000) and not the actual guitarix port (7000)

## Rixy (.env)
<img width="851" alt="rixy env" src="https://user-images.githubusercontent.com/16214942/127129381-449db824-37c8-4eb3-84e6-6f00ba78dc32.png">

## Rixy (yarn serve)
<img width="926" alt="rixy serve" src="https://user-images.githubusercontent.com/16214942/127129432-ae14e06a-b458-4bcc-bc99-36f284789f96.png">

## Web proxy
<img width="848" alt="webproxy" src="https://user-images.githubusercontent.com/16214942/127129504-489df74f-bc20-4090-8067-57a56c41623f.png">

## Guitarix
<img width="700" alt="guitarix" src="https://user-images.githubusercontent.com/16214942/127129652-20e45de3-21eb-4ffb-9d2e-e317621545a7.png">

## Rixy UI
<img width="912" alt="rixy ui" src="https://user-images.githubusercontent.com/16214942/127129742-13dfcaf1-875b-41ca-b43e-302caa614b11.png">

**Comment by fernando-inf** [comment]
Hola, gracias por la ayuda. Usted tenía razón, he revisado /etc/hosts y el localhost es 127.0.0.1:
```
127.0.0.1	localhost
127.0.1.1	pc01.pc	pc01

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters 
```
También corregí el puerto para RIXY a 8000. Ahora mi configuración de .env quedo como usted  lo sugirió:

```
VUE_APP_GUITARIX_HOST=127.0.0.1
VUE_APP_GUITARIX_PORT=8000

# comma seperated
VUE_APP_GUITARIX_IGNORE_FX=dubber,mbc,mbchor,mbclip,mbcs,mbd,mbdel,mbe,oscilloscope,seq

VUE_APP_DISABLE_LOGGER=0
```
RIXY funciona.


Pero sigo sin  hacer funcionar bien el SERVER de Guitarix. He optado por clonar guitarix desde git (`git clone.`.) y sus submodulos. Ahora Guitarix WEBUI funciona pero se conecta y desconecta:
```

/guitarix/trunk/webui $ websockify/websocketproxy.py --web=. '*':8000 127.0.0.1:7000

WebSocket server settings:
  - Listen on *:8000
  - Flash security policy server
  - Web server. Web root: /home/pc01/Descargas/Programas/guitarix/trunk/webui
  - No SSL/TLS support (no cert file)
  - proxying from *:8000 to 127.0.0.1:7000

  1: 127.0.0.1: Plain non-SSL (ws://) WebSocket connection
  1: 127.0.0.1: Version hybi-13, base64: 'False'
  1: connecting to: 127.0.0.1:7000
  1: handler exception: can't concat str to bytes
  2: 127.0.0.1: Plain non-SSL (ws://) WebSocket connection
  2: 127.0.0.1: Version hybi-13, base64: 'False'
  2: connecting to: 127.0.0.1:7000
  2: handler exception: can't concat str to bytes
```
Pero esto ya es problema de Guitarix WEBUI.

**Comment by GastroGeek** [comment]
@fernando-inf 

Extraño. No puedo ver nada fuera de lo común cuando comparo nuestras configuraciones ahora ...

¿Lo único que posiblemente sea diferente son las versiones de guitarix? (¿Asumo que comenzaste guitarix correctamente usando `guitarix -N`?)

Mina: 0.36.1
Instalado a través de: `apt-get install guitarix`

Entonces, ¿quizás puedas intentar instalar esa versión a través de `apt-get`? Curiosamente, luego usé el webui del último repositorio a través de `git clone` 👀

Finalmente, quizás revise la consola donde ejecutó `guitarix -N` para asegurarse de que no haya errores allí ...

-----------

Strange. I cannot see anything out of the ordinary when comparing our setups now...

The one thing that is possibly different is the guitarix versions? (I assume you started guitarix correctly using `guitarix -N`?)

Mine: 0.36.1
Installed via: `apt-get install guitarix`

So maybe you can try installing that version via `apt-get`? Interestingly, I then used the webui from the latest repo via `git clone` 👀 

Finally, perhaps check the console where you ran `guitarix -N` to make sure there are no errors there...

**Comment by GastroGeek** [comment]
También puede intentar ejecutar la versión de git usando:

```
guitarix -N -p 7000
```

Que se ejecuta con 'no gui' y 'puerto 7000' para el webui... tal vez cambiaron los puertos predeterminados o algo así 🤷

-------

You could also try running the git version using:

```
guitarix -N -p 7000
```

Which runs with as 'no gui' and 'port 7000' for the webui... perhaps they changed the default ports or something 🤷

**Comment by fernando-inf** [comment]
Si es extraño, estoy usando [DEBIAN 11 BULLSEYE (XFCE)](https://cdimage.debian.org/cdimage/unofficial/non-free/cd-including-firmware/bullseye_di_rc2-live+nonfree/amd64/iso-hybrid/) . He instalado la versión de repositorios de Debian (guitarix 0.42.1) y la versión GIT (guitarix 0.42.1 git). En ambas versiones WEBUI se conecta y desconecta una y otra vez con el error:  `handler exception: can't concat str to bytes`

En la consola: `$ guitarix -N `--> sin errores.
No hay diferencia con: `$ guitarix -N -p 7000`

**Comment by GastroGeek** [comment]
Bien, me actualicé a la misma versión de Debian y al mismo guitarix (0.42.1) y ... todavía me funciona 😬

No estoy seguro de qué podría estar causándolo ... ¿versión de Python (estoy usando 2.7.18)? versión de nodo? (estoy usando 12.20.1)

Ese mensaje de error parece estar relacionado con los websockets (entre rixy y webui) o alguna dependencia del sistema que causa problemas en Debian.

¡Avísame si lo haces funcionar!

-------

OK, so I upgraded to the same Debian version and the same guitarix (0.42.1) and... it still works for me 😬 

Not sure what could be causing it... python version (im using 2.7.18)? node version? (im using 12.20.1)

That error message feels like it might be related to either the websockets (between rixy and webui) or some system dependency causing issues on Debian.

Let me know if you get it working!

**Comment by fernando-inf** [comment]
Solucionado!. Solo tenía instalado `Python 3.9.2-3.`

Para solucionar el problema en Debian Bullseye RC2:
Instalar: `$ sudo apt install python2.7-minimal`
Luego:  .../guitarix/trunk/webui/websockify`$ python2.7 websocketproxy.py --web=../ '*':8000 127.0.0.1:7000`

Ahora funciona todo.
Sería bueno que en el futuro RIXY tuviera una opción para cambio de Banco y preset. También un botón para moverse hacia adelante y hacia atrás de las páginas.
Felicidades por el proyecto RIXY, linda interfaz.

¡Gracias por toda la ayuda!

**Comment by GastroGeek** [comment]
¡Viva! ¡Estoy feliz de que lo hayas hecho funcionar! ¡Felicidades!

Gracias por las amables palabras ... Rixy era originalmente solo para mi propio uso (lo estaba ejecutando en un pedal de guitarra basado en raspberry pi que hice) pero decidí hacerlo público en caso de que alguien quisiera una alternativa al webui (que personalmente , Sentí que no era muy bonito: 😬 )

Si encuentro algo de tiempo, ¡podría intentar agregar algunas funciones nuevas!

----------

Hurray!  I am happy you got it working! Congratulations!

Thanks for the kind words... Rixy was originally only for my own use (I was running it on a raspberry pi based guitar pedal I made) but I decided to make it public in case anyone wanted an alternative to the webui (which personally, I felt was not very pretty 😬 )

If I find some time, I might have a go at adding some new features!

**Comment by GastroGeek** [comment]
Cerrar este ticket ya que este problema en particular ahora se puede considerar resuelto.

---

Closing this ticket since this particular issue can now be considered resolved.
